services:
  app:
    depends_on:
      - modbus-server
    image: modbustohttp:latest
    container_name: modbustohttp
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "8080:8080"
    environment:
        - MODBUS_HOST=modbus-server
        - MODBUS_PORT=5020
        - MODBUS_SLAVE_ID=1
        - MODBUS_FUNCTIONS_SUPPORTED=ReadCoils,ReadDiscreteInputs,ReadHoldingRegisters,ReadInputRegisters,WriteSingleCoil,WriteMultipleCoils,WriteSingleRegister,WriteMultipleRegisters
        - HTTP_PORT=8080
        - HTTP_HOST=
  modbus-server:
    image: oitc/modbus-server:latest
    container_name: modbus-server
    ports:
        - "5020:5020"