// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: modbustohttp/v1alpha1/service.proto

package v1alpha1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha1 "modbustohttp/service/modbustohttp/v1alpha1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ModbusServiceName is the fully-qualified name of the ModbusService service.
	ModbusServiceName = "modbustohttp.v1alpha1.ModbusService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ModbusServiceReadHoldingRegistersProcedure is the fully-qualified name of the ModbusService's
	// ReadHoldingRegisters RPC.
	ModbusServiceReadHoldingRegistersProcedure = "/modbustohttp.v1alpha1.ModbusService/ReadHoldingRegisters"
	// ModbusServiceWriteSingleRegisterProcedure is the fully-qualified name of the ModbusService's
	// WriteSingleRegister RPC.
	ModbusServiceWriteSingleRegisterProcedure = "/modbustohttp.v1alpha1.ModbusService/WriteSingleRegister"
	// ModbusServiceReadCoilsProcedure is the fully-qualified name of the ModbusService's ReadCoils RPC.
	ModbusServiceReadCoilsProcedure = "/modbustohttp.v1alpha1.ModbusService/ReadCoils"
	// ModbusServiceReadDiscreteInputsProcedure is the fully-qualified name of the ModbusService's
	// ReadDiscreteInputs RPC.
	ModbusServiceReadDiscreteInputsProcedure = "/modbustohttp.v1alpha1.ModbusService/ReadDiscreteInputs"
	// ModbusServiceWriteSingleCoilProcedure is the fully-qualified name of the ModbusService's
	// WriteSingleCoil RPC.
	ModbusServiceWriteSingleCoilProcedure = "/modbustohttp.v1alpha1.ModbusService/WriteSingleCoil"
	// ModbusServiceWriteMultipleCoilsProcedure is the fully-qualified name of the ModbusService's
	// WriteMultipleCoils RPC.
	ModbusServiceWriteMultipleCoilsProcedure = "/modbustohttp.v1alpha1.ModbusService/WriteMultipleCoils"
	// ModbusServiceReadInputRegistersProcedure is the fully-qualified name of the ModbusService's
	// ReadInputRegisters RPC.
	ModbusServiceReadInputRegistersProcedure = "/modbustohttp.v1alpha1.ModbusService/ReadInputRegisters"
	// ModbusServiceWriteMultipleRegistersProcedure is the fully-qualified name of the ModbusService's
	// WriteMultipleRegisters RPC.
	ModbusServiceWriteMultipleRegistersProcedure = "/modbustohttp.v1alpha1.ModbusService/WriteMultipleRegisters"
	// ModbusServiceWriteBitInRegisterProcedure is the fully-qualified name of the ModbusService's
	// WriteBitInRegister RPC.
	ModbusServiceWriteBitInRegisterProcedure = "/modbustohttp.v1alpha1.ModbusService/WriteBitInRegister"
)

// ModbusServiceClient is a client for the modbustohttp.v1alpha1.ModbusService service.
type ModbusServiceClient interface {
	// ReadHoldingRegisters reads the holding registers from the modbus server
	ReadHoldingRegisters(context.Context, *connect.Request[v1alpha1.ReadHoldingRegistersRequest]) (*connect.Response[v1alpha1.ReadHoldingRegistersResponse], error)
	// WriteSingleRegister writes a single holding register to the modbus server
	WriteSingleRegister(context.Context, *connect.Request[v1alpha1.WriteSingleRegisterRequest]) (*connect.Response[v1alpha1.WriteSingleRegisterResponse], error)
	// ReadCoils reads the coils from the modbus server
	ReadCoils(context.Context, *connect.Request[v1alpha1.ReadCoilsRequest]) (*connect.Response[v1alpha1.ReadCoilsResponse], error)
	// ReadDiscreteInputs reads the discrete inputs from the modbus server
	ReadDiscreteInputs(context.Context, *connect.Request[v1alpha1.ReadDiscreteInputsRequest]) (*connect.Response[v1alpha1.ReadDiscreteInputsResponse], error)
	// WriteSingleCoil writes a single coil to the modbus server
	WriteSingleCoil(context.Context, *connect.Request[v1alpha1.WriteSingleCoilRequest]) (*connect.Response[v1alpha1.WriteSingleCoilResponse], error)
	// WriteMultipleCoils writes multiple coils to the modbus server
	WriteMultipleCoils(context.Context, *connect.Request[v1alpha1.WriteMultipleCoilsRequest]) (*connect.Response[v1alpha1.WriteMultipleCoilsResponse], error)
	// ReadInputRegisters reads the input registers from the modbus server
	ReadInputRegisters(context.Context, *connect.Request[v1alpha1.ReadInputRegistersRequest]) (*connect.Response[v1alpha1.ReadInputRegistersResponse], error)
	// WriteMultipleRegisters writes multiple holding registers to the modbus server
	WriteMultipleRegisters(context.Context, *connect.Request[v1alpha1.WriteMultipleRegistersRequest]) (*connect.Response[v1alpha1.WriteMultipleRegistersResponse], error)
	// WriteBitInRegister writes a single bit in a holding register to the modbus server
	WriteBitInRegister(context.Context, *connect.Request[v1alpha1.WriteBitInRegisterRequest]) (*connect.Response[v1alpha1.WriteBitInRegisterResponse], error)
}

// NewModbusServiceClient constructs a client for the modbustohttp.v1alpha1.ModbusService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewModbusServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ModbusServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	modbusServiceMethods := v1alpha1.File_modbustohttp_v1alpha1_service_proto.Services().ByName("ModbusService").Methods()
	return &modbusServiceClient{
		readHoldingRegisters: connect.NewClient[v1alpha1.ReadHoldingRegistersRequest, v1alpha1.ReadHoldingRegistersResponse](
			httpClient,
			baseURL+ModbusServiceReadHoldingRegistersProcedure,
			connect.WithSchema(modbusServiceMethods.ByName("ReadHoldingRegisters")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		writeSingleRegister: connect.NewClient[v1alpha1.WriteSingleRegisterRequest, v1alpha1.WriteSingleRegisterResponse](
			httpClient,
			baseURL+ModbusServiceWriteSingleRegisterProcedure,
			connect.WithSchema(modbusServiceMethods.ByName("WriteSingleRegister")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
		readCoils: connect.NewClient[v1alpha1.ReadCoilsRequest, v1alpha1.ReadCoilsResponse](
			httpClient,
			baseURL+ModbusServiceReadCoilsProcedure,
			connect.WithSchema(modbusServiceMethods.ByName("ReadCoils")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		readDiscreteInputs: connect.NewClient[v1alpha1.ReadDiscreteInputsRequest, v1alpha1.ReadDiscreteInputsResponse](
			httpClient,
			baseURL+ModbusServiceReadDiscreteInputsProcedure,
			connect.WithSchema(modbusServiceMethods.ByName("ReadDiscreteInputs")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		writeSingleCoil: connect.NewClient[v1alpha1.WriteSingleCoilRequest, v1alpha1.WriteSingleCoilResponse](
			httpClient,
			baseURL+ModbusServiceWriteSingleCoilProcedure,
			connect.WithSchema(modbusServiceMethods.ByName("WriteSingleCoil")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
		writeMultipleCoils: connect.NewClient[v1alpha1.WriteMultipleCoilsRequest, v1alpha1.WriteMultipleCoilsResponse](
			httpClient,
			baseURL+ModbusServiceWriteMultipleCoilsProcedure,
			connect.WithSchema(modbusServiceMethods.ByName("WriteMultipleCoils")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
		readInputRegisters: connect.NewClient[v1alpha1.ReadInputRegistersRequest, v1alpha1.ReadInputRegistersResponse](
			httpClient,
			baseURL+ModbusServiceReadInputRegistersProcedure,
			connect.WithSchema(modbusServiceMethods.ByName("ReadInputRegisters")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		writeMultipleRegisters: connect.NewClient[v1alpha1.WriteMultipleRegistersRequest, v1alpha1.WriteMultipleRegistersResponse](
			httpClient,
			baseURL+ModbusServiceWriteMultipleRegistersProcedure,
			connect.WithSchema(modbusServiceMethods.ByName("WriteMultipleRegisters")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
		writeBitInRegister: connect.NewClient[v1alpha1.WriteBitInRegisterRequest, v1alpha1.WriteBitInRegisterResponse](
			httpClient,
			baseURL+ModbusServiceWriteBitInRegisterProcedure,
			connect.WithSchema(modbusServiceMethods.ByName("WriteBitInRegister")),
			connect.WithClientOptions(opts...),
		),
	}
}

// modbusServiceClient implements ModbusServiceClient.
type modbusServiceClient struct {
	readHoldingRegisters   *connect.Client[v1alpha1.ReadHoldingRegistersRequest, v1alpha1.ReadHoldingRegistersResponse]
	writeSingleRegister    *connect.Client[v1alpha1.WriteSingleRegisterRequest, v1alpha1.WriteSingleRegisterResponse]
	readCoils              *connect.Client[v1alpha1.ReadCoilsRequest, v1alpha1.ReadCoilsResponse]
	readDiscreteInputs     *connect.Client[v1alpha1.ReadDiscreteInputsRequest, v1alpha1.ReadDiscreteInputsResponse]
	writeSingleCoil        *connect.Client[v1alpha1.WriteSingleCoilRequest, v1alpha1.WriteSingleCoilResponse]
	writeMultipleCoils     *connect.Client[v1alpha1.WriteMultipleCoilsRequest, v1alpha1.WriteMultipleCoilsResponse]
	readInputRegisters     *connect.Client[v1alpha1.ReadInputRegistersRequest, v1alpha1.ReadInputRegistersResponse]
	writeMultipleRegisters *connect.Client[v1alpha1.WriteMultipleRegistersRequest, v1alpha1.WriteMultipleRegistersResponse]
	writeBitInRegister     *connect.Client[v1alpha1.WriteBitInRegisterRequest, v1alpha1.WriteBitInRegisterResponse]
}

// ReadHoldingRegisters calls modbustohttp.v1alpha1.ModbusService.ReadHoldingRegisters.
func (c *modbusServiceClient) ReadHoldingRegisters(ctx context.Context, req *connect.Request[v1alpha1.ReadHoldingRegistersRequest]) (*connect.Response[v1alpha1.ReadHoldingRegistersResponse], error) {
	return c.readHoldingRegisters.CallUnary(ctx, req)
}

// WriteSingleRegister calls modbustohttp.v1alpha1.ModbusService.WriteSingleRegister.
func (c *modbusServiceClient) WriteSingleRegister(ctx context.Context, req *connect.Request[v1alpha1.WriteSingleRegisterRequest]) (*connect.Response[v1alpha1.WriteSingleRegisterResponse], error) {
	return c.writeSingleRegister.CallUnary(ctx, req)
}

// ReadCoils calls modbustohttp.v1alpha1.ModbusService.ReadCoils.
func (c *modbusServiceClient) ReadCoils(ctx context.Context, req *connect.Request[v1alpha1.ReadCoilsRequest]) (*connect.Response[v1alpha1.ReadCoilsResponse], error) {
	return c.readCoils.CallUnary(ctx, req)
}

// ReadDiscreteInputs calls modbustohttp.v1alpha1.ModbusService.ReadDiscreteInputs.
func (c *modbusServiceClient) ReadDiscreteInputs(ctx context.Context, req *connect.Request[v1alpha1.ReadDiscreteInputsRequest]) (*connect.Response[v1alpha1.ReadDiscreteInputsResponse], error) {
	return c.readDiscreteInputs.CallUnary(ctx, req)
}

// WriteSingleCoil calls modbustohttp.v1alpha1.ModbusService.WriteSingleCoil.
func (c *modbusServiceClient) WriteSingleCoil(ctx context.Context, req *connect.Request[v1alpha1.WriteSingleCoilRequest]) (*connect.Response[v1alpha1.WriteSingleCoilResponse], error) {
	return c.writeSingleCoil.CallUnary(ctx, req)
}

// WriteMultipleCoils calls modbustohttp.v1alpha1.ModbusService.WriteMultipleCoils.
func (c *modbusServiceClient) WriteMultipleCoils(ctx context.Context, req *connect.Request[v1alpha1.WriteMultipleCoilsRequest]) (*connect.Response[v1alpha1.WriteMultipleCoilsResponse], error) {
	return c.writeMultipleCoils.CallUnary(ctx, req)
}

// ReadInputRegisters calls modbustohttp.v1alpha1.ModbusService.ReadInputRegisters.
func (c *modbusServiceClient) ReadInputRegisters(ctx context.Context, req *connect.Request[v1alpha1.ReadInputRegistersRequest]) (*connect.Response[v1alpha1.ReadInputRegistersResponse], error) {
	return c.readInputRegisters.CallUnary(ctx, req)
}

// WriteMultipleRegisters calls modbustohttp.v1alpha1.ModbusService.WriteMultipleRegisters.
func (c *modbusServiceClient) WriteMultipleRegisters(ctx context.Context, req *connect.Request[v1alpha1.WriteMultipleRegistersRequest]) (*connect.Response[v1alpha1.WriteMultipleRegistersResponse], error) {
	return c.writeMultipleRegisters.CallUnary(ctx, req)
}

// WriteBitInRegister calls modbustohttp.v1alpha1.ModbusService.WriteBitInRegister.
func (c *modbusServiceClient) WriteBitInRegister(ctx context.Context, req *connect.Request[v1alpha1.WriteBitInRegisterRequest]) (*connect.Response[v1alpha1.WriteBitInRegisterResponse], error) {
	return c.writeBitInRegister.CallUnary(ctx, req)
}

// ModbusServiceHandler is an implementation of the modbustohttp.v1alpha1.ModbusService service.
type ModbusServiceHandler interface {
	// ReadHoldingRegisters reads the holding registers from the modbus server
	ReadHoldingRegisters(context.Context, *connect.Request[v1alpha1.ReadHoldingRegistersRequest]) (*connect.Response[v1alpha1.ReadHoldingRegistersResponse], error)
	// WriteSingleRegister writes a single holding register to the modbus server
	WriteSingleRegister(context.Context, *connect.Request[v1alpha1.WriteSingleRegisterRequest]) (*connect.Response[v1alpha1.WriteSingleRegisterResponse], error)
	// ReadCoils reads the coils from the modbus server
	ReadCoils(context.Context, *connect.Request[v1alpha1.ReadCoilsRequest]) (*connect.Response[v1alpha1.ReadCoilsResponse], error)
	// ReadDiscreteInputs reads the discrete inputs from the modbus server
	ReadDiscreteInputs(context.Context, *connect.Request[v1alpha1.ReadDiscreteInputsRequest]) (*connect.Response[v1alpha1.ReadDiscreteInputsResponse], error)
	// WriteSingleCoil writes a single coil to the modbus server
	WriteSingleCoil(context.Context, *connect.Request[v1alpha1.WriteSingleCoilRequest]) (*connect.Response[v1alpha1.WriteSingleCoilResponse], error)
	// WriteMultipleCoils writes multiple coils to the modbus server
	WriteMultipleCoils(context.Context, *connect.Request[v1alpha1.WriteMultipleCoilsRequest]) (*connect.Response[v1alpha1.WriteMultipleCoilsResponse], error)
	// ReadInputRegisters reads the input registers from the modbus server
	ReadInputRegisters(context.Context, *connect.Request[v1alpha1.ReadInputRegistersRequest]) (*connect.Response[v1alpha1.ReadInputRegistersResponse], error)
	// WriteMultipleRegisters writes multiple holding registers to the modbus server
	WriteMultipleRegisters(context.Context, *connect.Request[v1alpha1.WriteMultipleRegistersRequest]) (*connect.Response[v1alpha1.WriteMultipleRegistersResponse], error)
	// WriteBitInRegister writes a single bit in a holding register to the modbus server
	WriteBitInRegister(context.Context, *connect.Request[v1alpha1.WriteBitInRegisterRequest]) (*connect.Response[v1alpha1.WriteBitInRegisterResponse], error)
}

// NewModbusServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewModbusServiceHandler(svc ModbusServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	modbusServiceMethods := v1alpha1.File_modbustohttp_v1alpha1_service_proto.Services().ByName("ModbusService").Methods()
	modbusServiceReadHoldingRegistersHandler := connect.NewUnaryHandler(
		ModbusServiceReadHoldingRegistersProcedure,
		svc.ReadHoldingRegisters,
		connect.WithSchema(modbusServiceMethods.ByName("ReadHoldingRegisters")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	modbusServiceWriteSingleRegisterHandler := connect.NewUnaryHandler(
		ModbusServiceWriteSingleRegisterProcedure,
		svc.WriteSingleRegister,
		connect.WithSchema(modbusServiceMethods.ByName("WriteSingleRegister")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	modbusServiceReadCoilsHandler := connect.NewUnaryHandler(
		ModbusServiceReadCoilsProcedure,
		svc.ReadCoils,
		connect.WithSchema(modbusServiceMethods.ByName("ReadCoils")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	modbusServiceReadDiscreteInputsHandler := connect.NewUnaryHandler(
		ModbusServiceReadDiscreteInputsProcedure,
		svc.ReadDiscreteInputs,
		connect.WithSchema(modbusServiceMethods.ByName("ReadDiscreteInputs")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	modbusServiceWriteSingleCoilHandler := connect.NewUnaryHandler(
		ModbusServiceWriteSingleCoilProcedure,
		svc.WriteSingleCoil,
		connect.WithSchema(modbusServiceMethods.ByName("WriteSingleCoil")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	modbusServiceWriteMultipleCoilsHandler := connect.NewUnaryHandler(
		ModbusServiceWriteMultipleCoilsProcedure,
		svc.WriteMultipleCoils,
		connect.WithSchema(modbusServiceMethods.ByName("WriteMultipleCoils")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	modbusServiceReadInputRegistersHandler := connect.NewUnaryHandler(
		ModbusServiceReadInputRegistersProcedure,
		svc.ReadInputRegisters,
		connect.WithSchema(modbusServiceMethods.ByName("ReadInputRegisters")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	modbusServiceWriteMultipleRegistersHandler := connect.NewUnaryHandler(
		ModbusServiceWriteMultipleRegistersProcedure,
		svc.WriteMultipleRegisters,
		connect.WithSchema(modbusServiceMethods.ByName("WriteMultipleRegisters")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	modbusServiceWriteBitInRegisterHandler := connect.NewUnaryHandler(
		ModbusServiceWriteBitInRegisterProcedure,
		svc.WriteBitInRegister,
		connect.WithSchema(modbusServiceMethods.ByName("WriteBitInRegister")),
		connect.WithHandlerOptions(opts...),
	)
	return "/modbustohttp.v1alpha1.ModbusService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ModbusServiceReadHoldingRegistersProcedure:
			modbusServiceReadHoldingRegistersHandler.ServeHTTP(w, r)
		case ModbusServiceWriteSingleRegisterProcedure:
			modbusServiceWriteSingleRegisterHandler.ServeHTTP(w, r)
		case ModbusServiceReadCoilsProcedure:
			modbusServiceReadCoilsHandler.ServeHTTP(w, r)
		case ModbusServiceReadDiscreteInputsProcedure:
			modbusServiceReadDiscreteInputsHandler.ServeHTTP(w, r)
		case ModbusServiceWriteSingleCoilProcedure:
			modbusServiceWriteSingleCoilHandler.ServeHTTP(w, r)
		case ModbusServiceWriteMultipleCoilsProcedure:
			modbusServiceWriteMultipleCoilsHandler.ServeHTTP(w, r)
		case ModbusServiceReadInputRegistersProcedure:
			modbusServiceReadInputRegistersHandler.ServeHTTP(w, r)
		case ModbusServiceWriteMultipleRegistersProcedure:
			modbusServiceWriteMultipleRegistersHandler.ServeHTTP(w, r)
		case ModbusServiceWriteBitInRegisterProcedure:
			modbusServiceWriteBitInRegisterHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedModbusServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedModbusServiceHandler struct{}

func (UnimplementedModbusServiceHandler) ReadHoldingRegisters(context.Context, *connect.Request[v1alpha1.ReadHoldingRegistersRequest]) (*connect.Response[v1alpha1.ReadHoldingRegistersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("modbustohttp.v1alpha1.ModbusService.ReadHoldingRegisters is not implemented"))
}

func (UnimplementedModbusServiceHandler) WriteSingleRegister(context.Context, *connect.Request[v1alpha1.WriteSingleRegisterRequest]) (*connect.Response[v1alpha1.WriteSingleRegisterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("modbustohttp.v1alpha1.ModbusService.WriteSingleRegister is not implemented"))
}

func (UnimplementedModbusServiceHandler) ReadCoils(context.Context, *connect.Request[v1alpha1.ReadCoilsRequest]) (*connect.Response[v1alpha1.ReadCoilsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("modbustohttp.v1alpha1.ModbusService.ReadCoils is not implemented"))
}

func (UnimplementedModbusServiceHandler) ReadDiscreteInputs(context.Context, *connect.Request[v1alpha1.ReadDiscreteInputsRequest]) (*connect.Response[v1alpha1.ReadDiscreteInputsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("modbustohttp.v1alpha1.ModbusService.ReadDiscreteInputs is not implemented"))
}

func (UnimplementedModbusServiceHandler) WriteSingleCoil(context.Context, *connect.Request[v1alpha1.WriteSingleCoilRequest]) (*connect.Response[v1alpha1.WriteSingleCoilResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("modbustohttp.v1alpha1.ModbusService.WriteSingleCoil is not implemented"))
}

func (UnimplementedModbusServiceHandler) WriteMultipleCoils(context.Context, *connect.Request[v1alpha1.WriteMultipleCoilsRequest]) (*connect.Response[v1alpha1.WriteMultipleCoilsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("modbustohttp.v1alpha1.ModbusService.WriteMultipleCoils is not implemented"))
}

func (UnimplementedModbusServiceHandler) ReadInputRegisters(context.Context, *connect.Request[v1alpha1.ReadInputRegistersRequest]) (*connect.Response[v1alpha1.ReadInputRegistersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("modbustohttp.v1alpha1.ModbusService.ReadInputRegisters is not implemented"))
}

func (UnimplementedModbusServiceHandler) WriteMultipleRegisters(context.Context, *connect.Request[v1alpha1.WriteMultipleRegistersRequest]) (*connect.Response[v1alpha1.WriteMultipleRegistersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("modbustohttp.v1alpha1.ModbusService.WriteMultipleRegisters is not implemented"))
}

func (UnimplementedModbusServiceHandler) WriteBitInRegister(context.Context, *connect.Request[v1alpha1.WriteBitInRegisterRequest]) (*connect.Response[v1alpha1.WriteBitInRegisterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("modbustohttp.v1alpha1.ModbusService.WriteBitInRegister is not implemented"))
}
